import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import { it } from "node:test";
import type { NextAuthOptions } from "next-auth";
import type { NextRequest } from "next/server";
import { decode } from "next-auth/jwt";
import {
  createGoogleLinkIntentToken,
  googleLinkIntentCookieName,
  googleLinkStateBinding
} from "./google-link-intent";
import { runGoogleLinkRequest } from "./google-link-request";

const { AuthHandler } = createRequire(import.meta.url)("../../../node_modules/next-auth/core/index.js");
const secret = "synthetic-nextauth-secret-for-oauth-state";
const rawToken = createGoogleLinkIntentToken();
const cookie = `${googleLinkIntentCookieName(false)}=${rawToken}`;
const session = { userId: "opaque-user", sessionBinding: "a".repeat(64) };

function request(url: string, method = "GET") {
  return new Request(url, { method, headers: { cookie } }) as NextRequest;
}

function runtime(overrides: Partial<Parameters<typeof runGoogleLinkRequest>[4]> = {}) {
  return {
    authUrl: "https://app.example.com",
    secureCookie: false,
    session: async () => session,
    validate: async () => {},
    bind: async () => {},
    consume: async () => ({ status: "linked" as const }),
    ...overrides
  };
}

it("leaves all ordinary Google behavior untouched when no intent cookie exists", async () => {
  let called = 0;
  const result = await runGoogleLinkRequest(
    new Request("https://app.example.com/api/auth/signin/google", { method: "POST" }) as NextRequest,
    ["signin", "google"], { providers: [] }, async () => { called++; return new Response(); }, runtime()
  );
  assert.equal(result, null);
  assert.equal(called, 0);
});

it("binds the exact state returned by the NextAuth-controlled initiation response", async () => {
  let bound = "";
  const generatedState = "nextauth-generated-state";
  const result = await runGoogleLinkRequest(request("https://app.example.com/api/auth/signin/google", "POST"),
    ["signin", "google"], { providers: [] },
    async () => new Response(null, { status: 302, headers: { location: `https://accounts.example/authorize?state=${generatedState}` } }),
    runtime({ bind: async (_session, _token, state) => { bound = state; } })
  );
  assert.equal(result?.headers.get("location"), `https://accounts.example/authorize?state=${generatedState}`);
  assert.equal(bound, generatedState);
});

it("uses a request-local callback, consumes the exact callback state and clears the cookie", async () => {
  let consumedState = "";
  const baseSignIn = async () => { throw new Error("Normal bootstrap must not run for an explicit intent."); };
  const base: NextAuthOptions = { providers: [], callbacks: { signIn: baseSignIn } };
  const result = await runGoogleLinkRequest(request("https://app.example.com/api/auth/callback/google?state=bound-state"),
    ["callback", "google"], base, async options => {
      assert.notEqual(options.callbacks, base.callbacks);
      assert.equal(await options.callbacks!.signIn!({
        user: { id: "google-sub" },
        account: { provider: "google", type: "oauth", providerAccountId: "google-sub" },
        profile: { sub: "google-sub", email: "buyer@example.com", email_verified: true }
      }), true);
      return new Response(null, { status: 302, headers: { location: "https://app.example.com/dashboard" } });
    }, runtime({ consume: async (_session, _token, state) => {
      consumedState = state;
      return { status: "linked" as const };
    } }));
  assert.equal(consumedState, "bound-state");
  assert.match(result!.headers.get("set-cookie")!, /Max-Age=0/u);
});

it("fails closed before OAuth initiation when session or pending intent validation fails", async () => {
  let called = 0;
  const result = await runGoogleLinkRequest(request("https://app.example.com/api/auth/signin/google", "POST"),
    ["signin", "google"], { providers: [] }, async () => { called++; return new Response(); },
    runtime({ validate: async () => { throw new Error("invalid"); } }));
  assert.equal(called, 0);
  assert.equal(result?.status, 302);
  assert.match(result!.headers.get("set-cookie")!, /Max-Age=0/u);
});

it("binds the state generated by installed NextAuth 4.24.15 in one continuous initiation", async () => {
  const csrf = "synthetic-csrf";
  const csrfCookie = csrf + "|" + createHash("sha256").update(csrf + secret).digest("hex");
  const options: NextAuthOptions = {
    secret,
    session: { strategy: "jwt" },
    providers: [{
      id: "google", name: "Google", type: "oauth",
      authorization: { url: "https://accounts.example/authorize", params: {} },
      token: "https://accounts.example/token",
      userinfo: "https://accounts.example/userinfo",
      clientId: "client", clientSecret: "secret", checks: ["pkce", "state"],
      profile: profile => ({ id: String(profile.sub), email: String(profile.email) })
    }],
    logger: { error() {}, warn() {}, debug() {} }
  };
  let exactState = "";
  let signedState = "";
  let sawPkce = false;
  let boundState = "";
  const response = await runGoogleLinkRequest(
    request("https://app.example.com/api/auth/signin/google", "POST"), ["signin", "google"], options,
    async scoped => {
      const generated = await AuthHandler({
        req: {
          method: "POST", action: "signin", providerId: "google", query: {},
          headers: {}, cookies: { "next-auth.csrf-token": csrfCookie },
          body: { csrfToken: csrf, callbackUrl: "https://app.example.com", json: "true" }
        },
        options: scoped
      });
      exactState = String(new URL(generated.redirect).searchParams.get("state") ?? "");
      const stateCookie = generated.cookies.find(
        (value: { name: string }) => value.name === "next-auth.state");
      sawPkce = generated.cookies.some(
        (value: { name: string }) => value.name === "next-auth.pkce.code_verifier");
      assert.ok(stateCookie);
      const decoded = await decode({ secret, token: stateCookie.value, salt: stateCookie.name });
      signedState = String(decoded?.value ?? "");
      return new Response(null, { status: 302, headers: { location: generated.redirect } });
    },
    runtime({ bind: async (_session, _token, state) => { boundState = state; } })
  );
  const returnedState = new URL(response!.headers.get("location")!).searchParams.get("state");
  assert.ok(returnedState);
  assert.equal(exactState, returnedState);
  assert.equal(signedState, returnedState);
  assert.equal(boundState, returnedState);
  assert.equal(sawPkce, true);
  const alteredState = returnedState.slice(0, -1) + (returnedState.endsWith("a") ? "b" : "a");
  assert.notEqual(googleLinkStateBinding(alteredState, secret),
    googleLinkStateBinding(boundState, secret));
});
